name: prestamos-app

services:
  # Servicio Backend PHP
  - name: prestamos-backend
    type: web
    build:
      type: docker
      dockerfile: Dockerfile.backend
    ports:
      - port: 80
        protocol: http
    env:
      - key: DB_HOST
        value: ${DATABASE_URL}
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: prestamosdb
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
    regions:
      - fra
    instance_type: nano
    autoscaling:
      min: 1
      max: 1

  # Servicio Frontend React
  - name: prestamos-frontend
    type: web
    build:
      type: docker
      dockerfile: Dockerfile.frontend
    ports:
      - port: 80
        protocol: http
    env:
      - key: REACT_APP_API_URL
        value: https://prestamos-backend-${KOYEB_APP_ID}.koyeb.app
    regions:
      - fra
    instance_type: nano
    autoscaling:
      min: 1
      max: 1

# Base de datos PostgreSQL (usando servicio externo)
databases:
  - name: prestamos-db
    type: postgresql
    version: "15"
    plan: hobby