name: prestamos-app

services:
  # Servicio Backend PHP
  - name: prestamos-backend
    type: web
    build:
      type: docker
      dockerfile: Dockerfile.backend
      context: .
    ports:
      - port: 80
        protocol: http
    env:
      - key: DB_HOST
        value: ${DATABASE_URL}
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: prestamosdb
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
    regions:
      - fra
    instance_type: nano
    autoscaling:
      min: 1
      max: 2
    health_check:
      path: /api_postgres.php
      port: 80
      protocol: http
      initial_delay_seconds: 30
      timeout_seconds: 10

  # Servicio Frontend React
  - name: prestamos-frontend
    type: web
    build:
      type: docker
      dockerfile: Dockerfile.frontend
      context: .
    ports:
      - port: 80
        protocol: http
    env:
      - key: REACT_APP_API_URL
        value: https://prestamos-backend-${KOYEB_APP_ID}.koyeb.app
    regions:
      - fra
    instance_type: nano
    autoscaling:
      min: 1
      max: 2
    health_check:
      path: /
      port: 80
      protocol: http
      initial_delay_seconds: 60
      timeout_seconds: 10

# Base de datos PostgreSQL (usando servicio externo como Neon, Supabase o similar)
databases:
  - name: PrestamosEdin
    type: postgresql
    version: "15"
    plan: hobby