[phases.setup]
nixPkgs = ['php81', 'php81Extensions.pdo', 'php81Extensions.pdo_pgsql', 'php81Extensions.pgsql', 'php81Extensions.mbstring', 'php81Extensions.json']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php -S 0.0.0.0:$PORT index.php'