[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_pgsql', 'php82Extensions.pgsql', 'php82Extensions.mbstring', 'php82Extensions.json']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php -S 0.0.0.0:$PORT index.php'